- name: "Set systemd-timesyncd primary NTP servers in {{ timesyncd_conf_filepath }}"
  lineinfile:
    path: "{{ timesyncd_conf_filepath }}"
    regexp: >-
      ^#?NTP=
    line: >-
      NTP={{ primary_ntp_servers }}
    state: present
  notify: "restart-systemd-timesyncd"
  become: true
  become_user: root

- name: "Set systemd-timesyncd fallback NTP servers in {{ timesyncd_conf_filepath }}"
  lineinfile:
    path: "{{ timesyncd_conf_filepath }}"
    regexp: >-
      ^#?FallbackNTP=
    line: >-
      FallbackNTP={{ fallback_ntp_servers }}
    state: present
  notify: "restart-systemd-timesyncd"
  become: true
  become_user: root

- name: "Start and enable systemd-timesyncd"
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes
  become: true
  become_user: root

